apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-configmap"
  namespace: {{ .Release.Namespace }}
data:
  SPRING_DB_HOST: "{{ .Values.backend.SPRING_DB_HOST }}"
  SPRING_DB_PORT: "{{ .Values.backend.SPRING_DB_PORT }}"
  SPRING_DB_NAME: "{{ .Values.backend.SPRING_DB_NAME }}"
  SPRING_DB_USER: "{{ .Values.backend.SPRING_DB_USER }}"
  SPRING_DB_PASSWORD: "{{ .Values.backend.SPRING_DB_PASSWORD }}"