apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets: 
        - name: ibm-registry-secret
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.backend.image }}
        ports:
        - containerPort: {{ .Values.backend.containerPort }}
        env:
        {{- range $key, $value := .Values.backend.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
