backend:
  name: backend  # Nombre del backend
  replicas: 1  # Número de réplicas
  namespace: ""
  image:
    repository: ""
    tag: ""
  port: 8080  # Puerto de la aplicación
  SPRING_DB_HOST: ""
  SPRING_DB_PORT: ""
  SPRING_DB_NAME: ""
  SPRING_DB_USER: ""
  SPRING_DB_PASSWORD: ""
  resources:
    requests:
      memory: "128Mi"
      cpu: "250m"
    limits:
      memory: "256Mi"
      cpu: "500m"
  readinessProbe:
    initialDelaySeconds: 50
    periodSeconds: 10
  livenessProbe:
    initialDelaySeconds: 40
    periodSeconds: 10
  service:
    port: 80
    targetPort: 8080
    type: ClusterIP