apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Release.Name}}
  labels:
    app: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets: 
        - name: ibm-registry-secret
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.frontend.image }}
        ports:
        - containerPort: {{ .Values.frontend.containerPort }}
        resources:
          requests:
            memory: {{ .Values.frontend.resources.requests.memory }}
            cpu: {{ .Values.frontend.resources.requests.cpu }}
          limits:
            memory: {{ .Values.frontend.resources.limits.memory }}
            cpu: {{ .Values.frontend.resources.limits.cpu }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.containerPort }}
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          runAsUser: 1000690002
          runAsGroup: 1000690002
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          allowPrivilegeEscalation: false
          privileged: false
          capabilities:
            drop:
              - ALL
        volumeMounts:
          - name: nginx-cache
            mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}

