apiVersion: v1
kind: Service
metadata:
  name: 
    {{ .Release.Name }}-svc
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.containerPort }}
  type: {{ .Values.frontend.service.type }}
