name: ansible

on:
  workflow_dispatch:

jobs:
  install-ansible:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Paso 2: Configurar claves SSH
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PUBLIC_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa.pub
          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub

      # Paso 3: Instalar Ansible si no está instalado
      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt-get install -y ansible
          ansible --version

      # Paso 4: Llamar al playbook
      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook install_ansible_and_dependencies.yml
