name: Disaster Recovery
 
on:
  workflow_dispatch:
 
permissions:
  pull-requests: write
  contents: read
 
jobs:
  ansible:
    name: Ansible Workflow
    runs-on: self-hosted
 
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      STORAGE_ACCOUNT_NAME: stavsanchezdvfinlab
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
        
      
      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
 
      - name: Login to Azure with Service Principal
        run: |
          az login --service-principal \
            -u ${{ secrets.ARM_CLIENT_ID }} \
            -p ${{ secrets.ARM_CLIENT_SECRET }} \
            --tenant ${{ secrets.ARM_TENANT_ID }}
      - name: Install AzCopy
        run: |
          wget -O azcopy.tar.gz https://aka.ms/downloadazcopy-v10-linux
          tar -xvf azcopy.tar.gz
          sudo mv ./azcopy_linux_amd64_*/azcopy /usr/bin/azcopy
          azcopy --version
      - name: Obtener el último archivo de backup desde Azure Blob Storage
        run: |
          LAST_BLOB=$(az storage blob list \
            --account-name stajrochadvfinlab \
            --container-name backupcontainer \
            --query "[].{name:name, lastModified:properties.lastModified}" \
            --output json | jq -r 'sort_by(.lastModified) | .[-1].name')
            echo "LAST_BLOB=$LAST_BLOB" >> $GITHUB_ENV
 
      - name: Realizar copia a azure
        run: |
           azcopy copy "https://$STORAGE_ACCOUNT_NAME.blob.core.windows.net/$CONTAINER_BACKUP_NAME/$LAST_BLOB?${{ secrets.TOKEN_SAS }}" "/var/backups/$LAST_BLOB"
      - name: Execute Database Backup playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -i inventory.ini recuperacion.yaml
        working-directory: ansible
        env:
          LAST_BLOB: ${{ env.LAST_BLOB }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}