name: Infraestructure Apply
on:
  pull_request:
    types: [closed]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Move to iac
      run: |
        cd iac
        ls
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Set Terraform environment variables
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: echo "Environment variables set for Terraform"

    - name: Terraform Init
      working-directory: ./iac
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      run: terraform init


    - name: Terraform Apply
      working-directory: ./iac
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        VM_ADMIN_USERNAME: ${{ secrets.VM_ADMIN_USERNAME }}
        VM_ADMIN_PASSWORD: ${{ secrets.VM_ADMIN_PASSWORD }}
      run: terraform apply  -var "admin_username=${{ secrets.VM_ADMIN_USERNAME }}" -var "admin_password=${{ secrets.VM_ADMIN_PASSWORD }}" -auto-approve
