name: postgre

on:
  workflow_dispatch:

jobs:
  install-postgre:    
    runs-on: self-hosted
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v3
      
      - name: Agregar contraseña del secret
        working-directory: ansible  
        run: |
          echo ${{ secrets.KEY_SECRET }} > secreto.txt

      - name: ls
        working-directory: ansible  
        run: ls
      
      - name:  cat main.yaml
        working-directory: ansible  
        run: |
          cat main.yaml

      - name: ejecutar playbook
        working-directory: ansible  
        run: |
          ansible-playbook main.yaml -i inventory.ini --vault-password-file secreto.txt --become --extra-vars "ansible_become_password=${{ secrets.USER_PASSWORD }}"
