name: postgre

on:
  workflow_dispatch:

jobs:
  install-postgre:    
    runs-on: ubuntu-latest
    steps:
      - name: clonar repositorio
        uses: actions/checkout@v3
      
      - name: Agregar contraseña del secret
        working-directory: ansible  
        run: |
          echo ${{ secrets.KEY_SECRET }} > secreto.txt

      - name: ls
        working-directory: ansible  
        run: ls
      
      - name: Add SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PUBLIC_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa.pub
          echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          chmod 644 ~/.ssh/id_rsa.pub

      - name: ejecutar playbook
        working-directory: ansible  
        run: |
          ansible-playbook main.yaml -i inventory.ini --vault-password-file secreto.txt --become --extra-vars "ansible_become_password=${{ secrets.USER_PASSWORD }}"
