name: subirarchivos del chart
on:
  workflow_call:
    inputs:
      MICROSERVICE:
        required: true
        type: string
      
    secrets:
      APIKEY:
        required: true
      
 
jobs:
  empaquetarysubir:
    runs-on: ubuntu-latest
    steps:              
      - name: Install helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

      - name: Empaquetar
        run: |
          cd charts/
          helm package ./chart-${{ inputs.MICROSERVICE }} 
      - name: Instalar CLI de Azure
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Instalar IBM Cloud CLI
        run: |
          curl -fsSL https://clis.cloud.ibm.com/install/linux | sh
          ibmcloud plugin install container-registry -r 'IBM Cloud'
          ibmcloud plugin install container-service -r 'IBM Cloud'
          
      - name: Ibm Cloud Login
        run: |
          ibmcloud login --apikey ${{ secrets.APIKEY }} -r eu-gb
          ibmcloud target -g Stemdo_Sandbox
          ibmcloud cr login


      - name: Subir
        env:
          NAME_CHART: ${{ inputs.MICROSERVICE }}
        run: |
          CHART_FILE=$(ls -t *${NAME_CHART}-*.tgz | head -n 1)
          echo "Subiendo chart ${CHART_FILE}"
          helm push ${CHART_FILE} oci://uk.icr.io/cr-vsanchez


          
